### ISSUE TITLE
New home needed for debian package

### ISSUE THREAD

**Issue by colonelpopcorn** [reddec/trusted-cgi#12]
Bintray is no longer available since JFrog shut it down in May of 2021. See this article [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) for more details. If and when another home is found for binary hosting the install guide will need to be updated to reflect this change.

This project is really cool, BTW!

**Comment by c-nv-s** [comment]
might be a suitable alternative to Bintray https://www.getbalto.com/signup?plan=opensource
