### ISSUE TITLE
Token used before issued.

### ISSUE THREAD

**Issue by lemniskett** [reddec/trusted-cgi#15]
Hi! I stumbled upon this and excited to try it out, however I encountered this issue upon login:
```
Error: 403: token validation failed: Token used before issued
```
Downgrading to 0.3.6 seems to fix the issue.

**Comment by c-nv-s** [comment]
experiencing this same issue with latest build

**Comment by TheOneValen** [comment]
Same Problem with 0.3.7.

**Comment by BasToTheMax** [comment]
Having the same issue, but only with the light docker image. By using the default image, it works, for anyone wondering.
