### ISSUE TITLE
replace 'sh' for 'bash' in docker container

### ISSUE THREAD

**Issue by c-nv-s** [reddec/trusted-cgi#20]
In trying to avoid creating temporary files to store data which could just be kept in variables it is possible in bash to use the following syntax of process substitution and input redirection in order to pass data onto other commands:
```
{ read -d '' result ; }< <( curl http://myjsonapi.com/page1 | jq '.[0].somedatapoint' ) && anothercommand <<< "$result"
```

unfortunately this syntax isn't supported in 'sh' and an unexpected redirect error is received.
Is it possible to use bash in the docker containers instead.

**Comment by reddec** [comment]
Could you please elaborate?

I suppose you can just use `#!/usr/bin/env bash`. I also added `bash` to the full image

**Comment by reddec** [comment]
I am closing the issue for now. Feel free to re-open it.

**Comment by c-nv-s** [comment]
thanks for this, and thanks again for the very useful project
