### ISSUE TITLE
Link in README does not work (installation)

### ISSUE THREAD

**Issue by caminsha** [reddec/trusted-cgi#3]
I just wanted to read the installation instructions in the README-File.

I wanted to click on the following content:
      `See [installation manual](https://trusted-cgi.reddec.net/installation)`

Unfortunately the link did not work. Where can I find the  detailed installation instructions?
Thanks for updating.

**Comment by reddec** [comment]
My bad https://trusted-cgi.reddec.net/administrating/installation/

**Comment by reddec** [comment]
fixed

**Comment by caminsha** [comment]
That was fast. Thanks.
