### ISSUE TITLE
Split CLI Tool and Service debian packages

### ISSUE THREAD

**Issue by TheOneValen** [reddec/trusted-cgi#5]
First off: awesome project, much less overhead than all the other solutions I tried.

It would be great if the debian packages for the service (trusted-cgi) and the cli tool would be seperate. So you can install it on a server and use it remotely without installing the service, too.

Have a great day!

**Comment by JosXa** [comment]
Also makes for a cleaner system when you can define an alias that'll simply pull the latest version from Docker and run your command with the current directory mounted. I'm looking for something like
$ `docker run -it --rm --entrypoint /bin/sh reddec/trusted-cgi-cli:latest cgi-ctl <do-something>`

**Comment by reddec** [comment]
Thanks for your support!
* Yes, separation was planned. I sent PR to go-releaser package for separated packages and it was merged. Just forgot to update local build.
* That's doable, however, native version right now in a priority.

**Comment by reddec** [comment]
Available at least from 0.3.8
