### ISSUE TITLE
[Bug?] "new folder" creates a new *file*

### ISSUE THREAD

**Issue by JosXa** [reddec/trusted-cgi#7]
https://user-images.githubusercontent.com/7313176/105572103-5daaa580-5d55-11eb-98cd-a7564c790319.mp4

See screencast ⬆️ 

I am a little confused as to how it's supposed to behave here, is this a bug or is the problem between keyboard and chair?

**Comment by reddec** [comment]
Bug, confirmed

**Comment by reddec** [comment]
Fixed in master - scheduled for the release

**Comment by JosXa** [comment]
cool, thanks :)
