### ISSUE TITLE
Enhancement - Detecting Remote IP from behind reverse proxy

### ISSUE THREAD

**Issue by c-nv-s** [reddec/trusted-cgi#9]
If you have the trusted-cgi running behind a reverse proxy then the Remote IP address detected will be the internal IP address of the reverse proxy.

Is it possible to detect the client IP address using the Request Header Value e.g. X-Forwarded-For 
This is usually the header that the proxies pass on to the backend server so they are aware of the original client IP address.

**Comment by c-nv-s** [comment]
@reddec did you manage to progress this at all?

**Comment by reddec** [comment]
@c-nv-s Thanks for pinging! I am sorry but I didn't find free time for it yet. 
Just in case you will find a moment to do it by yourself, the PR should be trivial (except the new behavior should be enabled explicitly to avoid headers spoofing).

**Comment by c-nv-s** [comment]
@reddec re-pinging. Any chance you can revisit this request
